FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_GATEWAY_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_AUTH_URL
ARG NEXT_PUBLIC_AUTHORIZATION_URL
ARG NEXT_PUBLIC_AUTHORIZATION_CENTER_URL
ARG NEXT_PUBLIC_FILE_URL
ARG NEXT_PUBLIC_NOTIFICATION_URL
ARG NEXT_PUBLIC_APP_CODE
ARG NEXT_PUBLIC_SETUP_PASSWORD_URL

ENV NEXT_PUBLIC_API_GATEWAY_URL=${NEXT_PUBLIC_API_GATEWAY_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
ENV NEXT_PUBLIC_AUTHORIZATION_URL=${NEXT_PUBLIC_AUTHORIZATION_URL}
ENV NEXT_PUBLIC_AUTHORIZATION_CENTER_URL=${NEXT_PUBLIC_AUTHORIZATION_CENTER_URL}
ENV NEXT_PUBLIC_FILE_URL=${NEXT_PUBLIC_FILE_URL}
ENV NEXT_PUBLIC_NOTIFICATION_URL=${NEXT_PUBLIC_NOTIFICATION_URL}
ENV NEXT_PUBLIC_APP_CODE=${NEXT_PUBLIC_APP_CODE}
ENV NEXT_PUBLIC_SETUP_PASSWORD_URL=${NEXT_PUBLIC_SETUP_PASSWORD_URL}

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
