import { AUTH_SERVER_ENDPOINTS, INTERNAL_API_ROUTES } from "@/modules/opensuite-sdk/constants";

export const endpoints = {
  auth: AUTH_SERVER_ENDPOINTS,
  /** Internal Next.js API routes for secure cookie management */
  internal: INTERNAL_API_ROUTES,
  user: {
    list: { method: "GET", url: "/api/v1/users" },
    detail: (id: number) => ({ method: "GET", url: `/api/v1/users/${id}` }),
    create: { method: "POST", url: "/api/v1/users" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/users/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/users/${id}` }),
    signup: { method: "POST", url: "/api/v1/users/signup" },
    verifyEmail: { method: "GET", url: "/api/v1/users/verify-email" },
  },
  apps: {
    list: { method: "GET", url: "/api/v1/apps" },
    detail: (unique: string) => ({ method: "GET", url: `/api/v1/apps/${unique}` }),
    create: { method: "POST", url: "/api/v1/apps" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/apps/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/apps/${id}` }),
  },
  actions: {
    list: { method: "GET", url: "/api/v1/actions" },
    detail: (unique: string) => ({ method: "GET", url: `/api/v1/actions/${unique}` }),
    create: { method: "POST", url: "/api/v1/actions" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/actions/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/actions/${id}` }),
  },
  teams: {
    list: { method: "GET", url: "/api/v1/teams" },
    detail: (unique: string) => ({ method: "GET", url: `/api/v1/teams/${unique}` }),
    create: { method: "POST", url: "/api/v1/teams" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/teams/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/teams/${id}` }),
  },
  modules: {
    list: { method: "GET", url: "/api/v1/modules" },
    listByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/modules/by-app/${appCode}` }),
    detail: (unique: string) => ({ method: "GET", url: `/api/v1/modules/${unique}` }),
    create: { method: "POST", url: "/api/v1/modules" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/modules/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/modules/${id}` }),
  },
  permissions: {
    list: { method: "GET", url: "/api/v1/permissions" },
    listByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/permissions/by-app/${appCode}` }),
    detail: (id: number) => ({ method: "GET", url: `/api/v1/permissions/${id}` }),
    bulkCreate: { method: "POST", url: "/api/v1/permissions/bulk" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/permissions/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/permissions/${id}` }),
  },
  menus: {
    list: { method: "GET", url: "/api/v1/menus" },
    listByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/menus/by-app/${appCode}` }),
    detail: (id: number) => ({ method: "GET", url: `/api/v1/menus/${id}` }),
    bulkCreate: { method: "POST", url: "/api/v1/menus/bulk" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/menus/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/menus/${id}` }),
  },
  roles: {
    list: { method: "GET", url: "/api/v1/roles" },
    listByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/roles/by-app/${appCode}` }),
    detail: (id: number) => ({ method: "GET", url: `/api/v1/roles/${id}` }),
    create: { method: "POST", url: "/api/v1/roles" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/roles/${id}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/roles/${id}` }),
  },
  rolePermissions: {
    list: { method: "GET", url: "/api/v1/role-permissions" },
    listByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/role-permissions/by-app/${appCode}` }),
    listByRole: (roleCode: string) => ({ method: "GET", url: `/api/v1/role-permissions/by-role/${roleCode}` }),
    availablePermissionsByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/role-permissions/available-permissions/by-app/${appCode}` }),
    roleSummaries: { method: "GET", url: "/api/v1/role-permissions/roles" },
    roleSummariesByApp: (appCode: string) => ({ method: "GET", url: `/api/v1/role-permissions/roles/by-app/${appCode}` }),
    detail: (id: number) => ({ method: "GET", url: `/api/v1/role-permissions/${id}` }),
    create: { method: "POST", url: "/api/v1/role-permissions" },
    bulkCreate: { method: "POST", url: "/api/v1/role-permissions/bulk" },
    update: (id: number) => ({ method: "PUT", url: `/api/v1/role-permissions/${id}` }),
    updateByRole: (roleId: number) => ({ method: "PUT", url: `/api/v1/role-permissions/by-role/${roleId}` }),
    delete: (id: number) => ({ method: "DELETE", url: `/api/v1/role-permissions/${id}` }),
  },
} as const;
