export const routes = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  users: "/users",
  settings: "/settings",
  apps: "/apps",
  appCreate: "/apps/create",
  appDetail: (appCode: string) => `/apps/${appCode}`,
  appCredentials: (appCode: string) => `/apps/${appCode}/credentials`,
  appCredentialCreate: (appCode: string) => `/apps/${appCode}/credentials/create`,
  appSettings: (appCode: string) => `/apps/${appCode}/settings`,
  appModules: (appCode: string) => `/apps/${appCode}/modules`,
  appModuleCreate: (appCode: string) => `/apps/${appCode}/modules/create`,
  appModuleEdit: (appCode: string, moduleId: string) => `/apps/${appCode}/modules/${moduleId}/edit`,
  teams: "/teams",
  teamCreate: "/teams/create",
  teamDetail: (teamId: string) => `/teams/${teamId}`,
  actions: "/actions",
  actionCreate: "/actions/create",
} as const;
